// <auto-generated />
using System;
using CommerceSphere.CartService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace CommerceSphere.CartService.Infrastructure.Migrations
{
    [DbContext(typeof(CartDbContext))]
    partial class CartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CommerceSphere.CartService.Domain.Entities.Cart", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("status");
                b.Property<string>("IdempotencyKey").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("idempotency_key");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.Property<uint>("xmin").HasColumnType("xid").IsRowVersion().IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnName("xmin");

                b.HasKey("Id").HasName("PK_carts");
                b.HasIndex("UserId").HasDatabaseName("ix_carts_user_id");
                b.HasIndex("IdempotencyKey").IsUnique().HasDatabaseName("ix_carts_idempotency_key").HasFilter("idempotency_key IS NOT NULL");
                b.ToTable("carts");
            });

            modelBuilder.Entity("CommerceSphere.CartService.Domain.Entities.CartItem", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<Guid>("CartId").HasColumnType("uuid").HasColumnName("cart_id");
                b.Property<Guid>("ProductId").HasColumnType("uuid").HasColumnName("product_id");
                b.Property<string>("Sku").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("sku");
                b.Property<string>("ProductName").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("product_name");
                b.Property<int>("Quantity").HasColumnType("integer").HasColumnName("quantity");
                b.Property<decimal>("UnitPrice").HasPrecision(18, 4).HasColumnType("numeric(18,4)").HasColumnName("unit_price");
                b.Property<DateTime>("AddedAt").HasColumnType("timestamp with time zone").HasColumnName("added_at");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");

                b.HasKey("Id").HasName("PK_cart_items");
                b.HasIndex("CartId").HasDatabaseName("ix_cart_items_cart_id");
                b.HasIndex("ProductId").HasDatabaseName("ix_cart_items_product_id");
                b.ToTable("cart_items");
            });

            modelBuilder.Entity("CommerceSphere.CartService.Domain.Entities.CartItem", b =>
            {
                b.HasOne("CommerceSphere.CartService.Domain.Entities.Cart")
                    .WithMany("Items")
                    .HasForeignKey("CartId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CommerceSphere.CartService.Domain.Entities.Cart", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
        }
    }
}
