// <auto-generated />
using System;
using CommerceSphere.AuthService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommerceSphere.AuthService.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CommerceSphere.AuthService.Domain.Entities.RefreshToken", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<string>("Token").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("token");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("expires_at");
                b.Property<bool>("IsRevoked").HasColumnType("boolean").HasColumnName("is_revoked");
                b.Property<string>("ReplacedByToken").HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("replaced_by_token");
                b.Property<string>("CreatedByIp").IsRequired().HasMaxLength(45).HasColumnType("character varying(45)").HasColumnName("created_by_ip");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");

                b.HasKey("Id").HasName("PK_refresh_tokens");
                b.HasIndex("Token").IsUnique().HasDatabaseName("ix_refresh_tokens_token");
                b.HasIndex("UserId").HasDatabaseName("ix_refresh_tokens_user_id");
                b.ToTable("refresh_tokens");
            });

            modelBuilder.Entity("CommerceSphere.AuthService.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("email");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text").HasColumnName("password_hash");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("first_name");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("last_name");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("role");
                b.Property<bool>("IsActive").HasColumnType("boolean").HasColumnName("is_active");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("timestamp with time zone").HasColumnName("last_login_at");
                b.Property<uint>("xmin").HasColumnType("xid").IsRowVersion().IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnName("xmin");

                b.HasKey("Id").HasName("PK_users");
                b.HasIndex("Email").IsUnique().HasDatabaseName("ix_users_email");
                b.ToTable("users");
            });

            modelBuilder.Entity("CommerceSphere.AuthService.Domain.Entities.RefreshToken", b =>
            {
                b.HasOne("CommerceSphere.AuthService.Domain.Entities.User", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("CommerceSphere.AuthService.Domain.Entities.User", b =>
            {
                b.Navigation("RefreshTokens");
            });
#pragma warning restore 612, 618
        }
    }
}
