// <auto-generated />
using System;
using CommerceSphere.InventoryService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace CommerceSphere.InventoryService.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CommerceSphere.InventoryService.Domain.Entities.InventoryItem", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<Guid>("ProductId").HasColumnType("uuid").HasColumnName("product_id");
                b.Property<string>("Sku").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("sku");
                b.Property<int>("QuantityOnHand").HasColumnType("integer").HasColumnName("quantity_on_hand");
                b.Property<int>("QuantityReserved").HasColumnType("integer").HasColumnName("quantity_reserved");
                b.Property<int>("ReorderLevel").HasColumnType("integer").HasColumnName("reorder_level");
                b.Property<bool>("IsActive").HasColumnType("boolean").HasColumnName("is_active");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.Property<uint>("xmin").HasColumnType("xid").IsRowVersion().IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnName("xmin");

                b.HasKey("Id").HasName("PK_inventory_items");
                b.HasIndex("ProductId").IsUnique().HasDatabaseName("ix_inventory_items_product_id");
                b.HasIndex(new[] { "ProductId", "Sku" }).IsUnique().HasDatabaseName("ix_inventory_items_product_sku");
                b.HasIndex("Sku").HasDatabaseName("ix_inventory_items_sku");
                b.ToTable("inventory_items");
            });

            modelBuilder.Entity("CommerceSphere.InventoryService.Domain.Entities.Reservation", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<Guid>("CartId").HasColumnType("uuid").HasColumnName("cart_id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("status");
                b.Property<string>("IdempotencyKey").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("idempotency_key");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.Property<uint>("xmin").HasColumnType("xid").IsRowVersion().IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnName("xmin");

                b.HasKey("Id").HasName("PK_reservations");
                b.HasIndex("CartId").HasDatabaseName("ix_reservations_cart_id");
                b.HasIndex("IdempotencyKey").IsUnique().HasDatabaseName("ix_reservations_idempotency_key");
                b.ToTable("reservations");

                b.OwnsMany("CommerceSphere.InventoryService.Domain.Entities.ReservationItem", "Items", b1 =>
                {
                    b1.Property<Guid>("Id").HasColumnName("id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b1.Property<Guid>("reservation_id").HasColumnType("uuid");
                    b1.Property<Guid>("ProductId").HasColumnType("uuid").HasColumnName("product_id");
                    b1.Property<string>("Sku").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("sku");
                    b1.Property<int>("Quantity").HasColumnType("integer").HasColumnName("quantity");
                    b1.Property<decimal>("UnitPrice").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("unit_price");
                    b1.HasKey("Id");
                    b1.HasIndex("reservation_id");
                    b1.ToTable("reservation_items");
                    b1.WithOwner().HasForeignKey("reservation_id");
                });

                b.Navigation("Items");
            });
#pragma warning restore 612, 618
        }
    }
}
