// <auto-generated />
using System;
using CommerceSphere.ProductService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace CommerceSphere.ProductService.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CommerceSphere.ProductService.Domain.Entities.Product", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("name");
                b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)").HasColumnName("description");
                b.Property<string>("Sku").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("sku");
                b.Property<decimal>("Price").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasColumnName("price");
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("category");
                b.Property<string>("ImageUrl").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("image_url");
                b.Property<bool>("IsActive").HasColumnType("boolean").HasColumnName("is_active");
                b.Property<int>("Stock").HasColumnType("integer").HasColumnName("stock");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.Property<uint>("xmin").HasColumnType("xid").IsRowVersion().IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnName("xmin");

                b.HasKey("Id").HasName("PK_products");
                b.HasIndex("Sku").IsUnique().HasDatabaseName("ix_products_sku");
                b.HasIndex("Category").HasDatabaseName("ix_products_category");
                b.ToTable("products");
            });
#pragma warning restore 612, 618
        }
    }
}
